@startuml crud_device_conroller
title Smart Home Devices Management Code Diagram

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

class User {
  +String login
  +List<Device> devices
}

class Device {
  +String id
  +String name
  +String type
  +String location
  +String value
  +String unit
  +String status
  +Date lastUpdated
  +Date createdAt
  +void create()
  +void read()
  +void update()
  +void delete()
}

User "1" -- "0..*" Device : has

@enduml