## Запуск: docker compose up -d
## Остановка: docker compose down

services:
  postgres:
    image: postgres:16-alpine
    container_name: smarthome-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      ## Для перезапуска с повторной инициализацией нужно удалить том postgres_data
      ## например, docker compose down -v перед docker compose up -d.
      - postgres_data:/var/lib/postgresql/data
      - ./smart_home/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - smarthome-network

  temperature-api:
    build:
      context: ./temperature_api
      dockerfile: Dockerfile
    container_name: temperature-api-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8081:8081"
    restart: unless-stopped
    networks:
      - smarthome-network

  app:
    build:
      context: ./smart_home
      dockerfile: Dockerfile
    container_name: smarthome-app
    depends_on:
      postgres:
        condition: service_healthy
      temperature-api:
        condition: service_started
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - TEMPERATURE_API_URL=http://temperature-api:8081
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - smarthome-network

volumes:
  postgres_data:

networks:
  smarthome-network:
    driver: bridge